# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vc0rkE5mBRuEpGqGHQ-p6tiAn8B5L5FZ



"""  # НОВЫЙ ТЕСТ"""

# ============================================================================
# КОНВЕРТАЦИЯ YOLO → CLASSIFICATION + ОБУЧЕНИЕ MobileNetV3+Bio
# ОПТИМИЗИРОВАНО ДЛЯ GOOGLE COLAB FREE TIER (T4)
# ============================================================================

import onnx
import seaborn as sns
from sklearn.metrics import classification_report, confusion_matrix
from google.colab import drive
import matplotlib.pyplot as plt
from PIL import Image
import mediapipe as mp
from torch.amp import autocast, GradScaler  # ← Исправлен импорт
from torchvision import models
import torchvision.transforms as transforms
from torch.utils.data import Dataset, DataLoader
import torch.optim as optim
import torch.nn as nn
import torch
import yaml
import random
from collections import Counter, defaultdict
from tqdm.notebook import tqdm
from pathlib import Path
import pickle
import shutil
import numpy as np
import cv2
import os
!pip install mediapipe - q


# Google Drive
drive.mount('/content/drive')

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"🖥️ Device: {device}")
if device.type == 'cuda':
    print(f"🎮 GPU: {torch.cuda.get_device_name(0)}")

# ============================================================================
# ЧАСТЬ 2: КОНФИГУРАЦИЯ
# ============================================================================

# Путь к YOLO датасету (измени на свой)
YOLO_DATASET_PATH = Path("/content/drowsiness2-1")

# Путь для сохранения классификационного датасета
CLASSIFICATION_DATASET_PATH = Path("/content/classification_dataset")

# Путь для кэша биометрии
BIO_CACHE_PATH = Path("/content/bio_cache.pkl")

# Маппинг классов YOLO → Classification
# YOLO classes: 0=awake, 1=look-forward, 2=sleep, 3=yawn
CLASS_MAPPING = {
    0: 0,  # awake → Active
    1: 0,  # look-forward → Active
    2: 1,  # sleep → Fatigue
    3: 1,  # yawn → Fatigue
}

CLASS_NAMES = ['active', 'fatigue']
YOLO_CLASS_NAMES = ['awake', 'look-forward', 'sleep', 'yawn']

# Параметры обработки
MIN_BBOX_SIZE = 50      # Минимальный размер bbox в пикселях
PADDING_RATIO = 0.2     # Расширение bbox на 20% для захвата контекста
OUTPUT_SIZE = 256       # Размер выходного изображения

# Параметры обучения (оптимизированы для Colab Free)
BATCH_SIZE = 32         # ← Уменьшено с 64
NUM_WORKERS = 2         # ← Уменьшено с 4 (Colab рекомендует максимум 2)
EPOCHS = 30
LEARNING_RATE = 1e-4

# ============================================================================
# ЧАСТЬ 3: ПАРСИНГ YOLO АННОТАЦИЙ
# ============================================================================


def parse_yolo_label(label_path, img_width, img_height):
    """
    Парсит YOLO label файл и возвращает список bbox'ов

    YOLO формат: class_id x_center y_center width height (всё нормализовано 0-1)
    """
    boxes = []

    if not os.path.exists(label_path):
        return boxes

    with open(label_path, 'r') as f:
        for line in f:
            parts = line.strip().split()
            if len(parts) < 5:
                continue

            class_id = int(parts[0])
            x_center = float(parts[1])
            y_center = float(parts[2])
            width = float(parts[3])
            height = float(parts[4])

            # Конвертация из нормализованных в пиксельные координаты
            x_center_px = x_center * img_width
            y_center_px = y_center * img_height
            width_px = width * img_width
            height_px = height * img_height

            # Конвертация в (x1, y1, x2, y2)
            x1 = int(x_center_px - width_px / 2)
            y1 = int(y_center_px - height_px / 2)
            x2 = int(x_center_px + width_px / 2)
            y2 = int(y_center_px + height_px / 2)

            boxes.append({
                'class_id': class_id,
                'bbox': (x1, y1, x2, y2),
                'yolo_class': YOLO_CLASS_NAMES[class_id] if class_id < len(YOLO_CLASS_NAMES) else 'unknown'
            })

    return boxes


def expand_bbox(bbox, img_width, img_height, padding_ratio=0.2):
    """Расширяет bbox для захвата контекста"""
    x1, y1, x2, y2 = bbox

    w = x2 - x1
    h = y2 - y1

    pad_w = int(w * padding_ratio)
    pad_h = int(h * padding_ratio)

    x1 = max(0, x1 - pad_w)
    y1 = max(0, y1 - pad_h)
    x2 = min(img_width, x2 + pad_w)
    y2 = min(img_height, y2 + pad_h)

    return (x1, y1, x2, y2)

# ============================================================================
# ЧАСТЬ 4: КОНВЕРТАЦИЯ ДАТАСЕТА
# ============================================================================


def convert_yolo_to_classification(yolo_path, output_path, use_crops=True):
    """Конвертирует YOLO датасет в классификационный"""

    yolo_path = Path(yolo_path)
    output_path = Path(output_path)

    # Очищаем output если существует
    if output_path.exists():
        shutil.rmtree(output_path)

    stats = {'total': 0, 'success': 0, 'failed': 0, 'per_class': Counter()}

    for split in ['train', 'valid', 'test']:
        images_dir = yolo_path / split / 'images'
        labels_dir = yolo_path / split / 'labels'

        if not images_dir.exists():
            print(f"⚠️ Папка {images_dir} не найдена, пропускаем...")
            continue

        print(f"\n📂 Обработка {split}...")

        # Создаём выходные папки
        for class_name in CLASS_NAMES:
            (output_path / split / class_name).mkdir(parents=True, exist_ok=True)

        # Обрабатываем изображения
        image_files = list(images_dir.glob('*.jpg')) + \
            list(images_dir.glob('*.png'))

        for img_path in tqdm(image_files, desc=f"  {split}"):
            stats['total'] += 1

            img = cv2.imread(str(img_path))
            if img is None:
                stats['failed'] += 1
                continue

            img_height, img_width = img.shape[:2]

            label_path = labels_dir / (img_path.stem + '.txt')
            boxes = parse_yolo_label(label_path, img_width, img_height)

            if len(boxes) == 0:
                stats['failed'] += 1
                continue

            for i, box_info in enumerate(boxes):
                yolo_class_id = box_info['class_id']

                if yolo_class_id not in CLASS_MAPPING:
                    continue

                classification_class = CLASS_MAPPING[yolo_class_id]
                class_name = CLASS_NAMES[classification_class]

                if use_crops:
                    bbox = box_info['bbox']
                    bbox = expand_bbox(
                        bbox, img_width, img_height, PADDING_RATIO)
                    x1, y1, x2, y2 = bbox

                    if (x2 - x1) < MIN_BBOX_SIZE or (y2 - y1) < MIN_BBOX_SIZE:
                        continue

                    crop = img[y1:y2, x1:x2]
                    crop = cv2.resize(crop, (OUTPUT_SIZE, OUTPUT_SIZE))
                    output_img = crop
                else:
                    output_img = cv2.resize(img, (OUTPUT_SIZE, OUTPUT_SIZE))

                output_filename = f"{img_path.stem}_box{i}.jpg"
                output_filepath = output_path / split / class_name / output_filename

                cv2.imwrite(str(output_filepath), output_img)

                stats['success'] += 1
                stats['per_class'][f"{split}_{class_name}"] += 1

    # Статистика
    print("\n" + "=" * 60)
    print("📊 СТАТИСТИКА КОНВЕРТАЦИИ")
    print("=" * 60)
    print(f"Всего изображений: {stats['total']}")
    print(f"Успешно: {stats['success']}")
    print(f"Пропущено: {stats['failed']}")
    print("\nПо классам:")

    for split in ['train', 'valid', 'test']:
        print(f"\n  {split}:")
        for class_name in CLASS_NAMES:
            key = f"{split}_{class_name}"
            count = stats['per_class'].get(key, 0)
            print(f"    {class_name}: {count}")

    return output_path

# ============================================================================
# ЗАПУСК КОНВЕРТАЦИИ
# ============================================================================


print("🔄 Конвертация YOLO → Classification...")

converted_dataset_path = convert_yolo_to_classification(
    yolo_path=YOLO_DATASET_PATH,
    output_path=CLASSIFICATION_DATASET_PATH,
    use_crops=True
)

print(f"\n✅ Датасет сохранён в: {converted_dataset_path}")

# ============================================================================
# ЧАСТЬ 5: БИОМЕТРИЧЕСКИЙ ЭКСТРАКТОР
# ============================================================================


class RobustBiometricExtractor:
    """Извлечение биометрических признаков с MediaPipe"""

    def __init__(self):
        self.face_mesh = mp.solutions.face_mesh.FaceMesh(
            static_image_mode=True,
            max_num_faces=1,
            refine_landmarks=True,
            min_detection_confidence=0.3
        )

        self.LEFT_EYE = [362, 385, 387, 263, 373, 380]
        self.RIGHT_EYE = [33, 160, 158, 133, 153, 144]

    def _distance(self, p1, p2):
        return np.sqrt((p1.x - p2.x)**2 + (p1.y - p2.y)**2)

    def _calculate_ear(self, landmarks, indices):
        try:
            pts = [landmarks[i] for i in indices]
            v1 = self._distance(pts[1], pts[5])
            v2 = self._distance(pts[2], pts[4])
            h = self._distance(pts[0], pts[3])
            if h < 0.01:
                return 0.0
            ear = (v1 + v2) / (2.0 * h)
            return ear if 0.05 < ear < 0.5 else 0.0
        except:
            return 0.0

    def _calculate_mar(self, landmarks):
        try:
            v = self._distance(landmarks[13], landmarks[14])
            h = self._distance(landmarks[61], landmarks[291])
            if h < 0.01:
                return 0.0
            return v / h
        except:
            return 0.0

    def _calculate_pose(self, landmarks):
        try:
            nose = landmarks[1]
            left_eye = landmarks[263]
            right_eye = landmarks[33]

            mid_x = (left_eye.x + right_eye.x) / 2
            mid_y = (left_eye.y + right_eye.y) / 2

            yaw = (nose.x - mid_x) * 100
            pitch = (nose.y - mid_y) * 100
            roll = (left_eye.y - right_eye.y) * 100

            return yaw, pitch, roll
        except:
            return 0.0, 0.0, 0.0

    def extract(self, image_bgr):
        """Возвращает 8 биометрических признаков"""
        features = np.zeros(8, dtype=np.float32)

        if image_bgr is None:
            return features

        image_rgb = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2RGB)
        results = self.face_mesh.process(image_rgb)

        if results.multi_face_landmarks:
            lm = results.multi_face_landmarks[0].landmark

            l_ear = self._calculate_ear(lm, self.LEFT_EYE)
            r_ear = self._calculate_ear(lm, self.RIGHT_EYE)
            mar = self._calculate_mar(lm)
            yaw, pitch, roll = self._calculate_pose(lm)

            features[0] = l_ear
            features[1] = r_ear
            features[2] = (l_ear + r_ear) / 2.0
            features[3] = mar
            features[4] = yaw
            features[5] = pitch
            features[6] = roll
            features[7] = 1.0 if l_ear > 0 else 0.0

        return features


# Создаём глобальный экстрактор
bio_extractor = RobustBiometricExtractor()
print("✅ Биометрический экстрактор создан")

# ============================================================================
# ЧАСТЬ 6: ПРЕДВАРИТЕЛЬНОЕ КЭШИРОВАНИЕ БИОМЕТРИИ
# ЭТО КЛЮЧЕВОЕ ИСПРАВЛЕНИЕ - ДЕЛАЕТСЯ ОДИН РАЗ!
# ============================================================================


def precompute_biometrics(dataset_path, cache_path):
    """
    Извлекает биометрию из ВСЕХ изображений ОДИН РАЗ и сохраняет в файл.
    Это занимает 2-5 минут, но потом обучение будет быстрым!
    """

    cache = {}
    dataset_path = Path(dataset_path)

    total_images = 0
    successful = 0

    for split in ['train', 'valid', 'test']:
        for class_name in CLASS_NAMES:
            class_dir = dataset_path / split / class_name
            if not class_dir.exists():
                continue

            images = list(class_dir.glob('*.jpg')) + \
                list(class_dir.glob('*.png'))

            for img_path in tqdm(images, desc=f"📊 {split}/{class_name}"):
                total_images += 1
                img = cv2.imread(str(img_path))

                if img is not None:
                    features = bio_extractor.extract(img)
                    cache[str(img_path)] = features
                    if features[7] > 0:  # Face detected
                        successful += 1
                else:
                    cache[str(img_path)] = np.zeros(8, dtype=np.float32)

    # Сохраняем кэш
    with open(cache_path, 'wb') as f:
        pickle.dump(cache, f)

    print(f"\n✅ Кэш биометрии создан:")
    print(f"   Всего изображений: {total_images}")
    print(
        f"   Лицо найдено: {successful} ({100*successful/total_images:.1f}%)")
    print(f"   Сохранено в: {cache_path}")

    return cache

# ============================================================================
# ЗАГРУЗКА ИЛИ СОЗДАНИЕ КЭША
# ============================================================================


print("\n" + "=" * 60)
print("🔄 КЭШИРОВАНИЕ БИОМЕТРИИ")
print("=" * 60)

if BIO_CACHE_PATH.exists():
    print("📂 Найден существующий кэш, загружаем...")
    with open(BIO_CACHE_PATH, 'rb') as f:
        bio_cache = pickle.load(f)
    print(f"✅ Загружено {len(bio_cache)} записей из кэша")
else:
    print("⏳ Кэш не найден, создаём (это займёт 2-5 минут)...")
    bio_cache = precompute_biometrics(
        CLASSIFICATION_DATASET_PATH, BIO_CACHE_PATH)

# ============================================================================
# ЧАСТЬ 7: БЫСТРЫЙ DATASET (использует кэш вместо MediaPipe)
# ============================================================================


class FastFatigueDataset(Dataset):
    """
    Оптимизированный Dataset - биометрия берётся из кэша!
    Это делает обучение в 20-50 раз быстрее.
    """

    def __init__(self, root_dir, split, transform, bio_cache):
        self.root_dir = Path(root_dir) / split
        self.transform = transform
        self.bio_cache = bio_cache
        self.samples = []

        # Загружаем все изображения
        for class_idx, class_name in enumerate(CLASS_NAMES):
            class_dir = self.root_dir / class_name
            if class_dir.exists():
                for img_path in class_dir.glob('*.*'):
                    if img_path.suffix.lower() in ['.jpg', '.jpeg', '.png']:
                        self.samples.append({
                            'path': str(img_path),
                            'label': class_idx
                        })

        # Статистика
        labels = [s['label'] for s in self.samples]
        counter = Counter(labels)
        print(f"[{split}] Загружено {len(self.samples)} изображений")
        for idx, name in enumerate(CLASS_NAMES):
            print(f"  - {name}: {counter.get(idx, 0)}")

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        sample = self.samples[idx]

        # Загрузка изображения
        img = cv2.imread(sample['path'])
        if img is None:
            img = np.zeros((224, 224, 3), dtype=np.uint8)

        # ⚡ Биометрия ИЗ КЭША (мгновенно!)
        bio = self.bio_cache.get(sample['path'], np.zeros(8, dtype=np.float32))

        # Конвертация BGR → RGB для PyTorch
        img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        img_pil = Image.fromarray(img_rgb)

        # Применяем трансформации
        if self.transform:
            img_tensor = self.transform(img_pil)
        else:
            img_tensor = transforms.ToTensor()(img_pil)

        return img_tensor, torch.tensor(bio, dtype=torch.float32), sample['label']

# ============================================================================
# ЧАСТЬ 8: ТРАНСФОРМАЦИИ
# ============================================================================


IMAGENET_MEAN = [0.485, 0.456, 0.406]
IMAGENET_STD = [0.229, 0.224, 0.225]

train_transforms = transforms.Compose([
    transforms.Resize((256, 256)),
    transforms.RandomCrop(224),
    transforms.RandomHorizontalFlip(p=0.3),
    transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.1),
    transforms.RandomRotation(10),
    transforms.ToTensor(),
    transforms.Normalize(mean=IMAGENET_MEAN, std=IMAGENET_STD)
])

val_transforms = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=IMAGENET_MEAN, std=IMAGENET_STD)
])

# ============================================================================
# ЧАСТЬ 8: МОДЕЛЬ
# ============================================================================


class MobileNetV3BiometricFusion(nn.Module):
    """MobileNetV3-Large + Биометрические признаки с Attention Fusion"""

    def __init__(self, num_bio_features=8, hidden_dim=256, num_classes=2, dropout=0.4):
        super().__init__()

        # Visual Backbone
        self.backbone = models.mobilenet_v3_large(weights='IMAGENET1K_V1')
        backbone_out = self.backbone.classifier[0].in_features  # 960
        self.backbone.classifier = nn.Identity()

        # Visual Projector
        self.visual_proj = nn.Sequential(
            nn.Linear(backbone_out, hidden_dim),
            nn.BatchNorm1d(hidden_dim),
            nn.ReLU(),
            nn.Dropout(dropout)
        )

        # Biometric Encoder
        self.bio_encoder = nn.Sequential(
            nn.Linear(num_bio_features, 64),
            nn.BatchNorm1d(64),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(64, 128),
            nn.BatchNorm1d(128),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(128, hidden_dim),
            nn.BatchNorm1d(hidden_dim),
            nn.ReLU()
        )

        # Adaptive Fusion Gate
        self.fusion_gate = nn.Sequential(
            nn.Linear(hidden_dim * 2, 64),
            nn.ReLU(),
            nn.Linear(64, 2),
            nn.Softmax(dim=1)
        )

        # Classifier
        self.classifier = nn.Sequential(
            nn.Linear(hidden_dim, 128),
            nn.BatchNorm1d(128),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(128, num_classes)
        )

    def forward(self, image, bio_features):
        v = self.visual_proj(self.backbone(image))
        b = self.bio_encoder(bio_features)

        concat = torch.cat([v, b], dim=1)
        weights = self.fusion_gate(concat)

        fused = weights[:, 0:1] * v + weights[:, 1:2] * b

        return self.classifier(fused)

    def get_fusion_weights(self, image, bio_features):
        """Для анализа: какой модальности модель доверяет больше"""
        v = self.visual_proj(self.backbone(image))
        b = self.bio_encoder(bio_features)
        concat = torch.cat([v, b], dim=1)
        return self.fusion_gate(concat)


print("✅ Модель определена")

# ============================================================================
# ЧАСТЬ 9: ФУНКЦИЯ ОБУЧЕНИЯ
# ============================================================================


def train_model(model, train_loader, valid_loader, epochs=30, lr=1e-4):
    """Обучение с логированием и сохранением лучшей модели"""

    model = model.to(device)

    optimizer = optim.AdamW(model.parameters(), lr=lr, weight_decay=1e-4)
    scheduler = optim.lr_scheduler.CosineAnnealingWarmRestarts(
        optimizer, T_0=10, eta_min=1e-6)
    criterion = nn.CrossEntropyLoss()
    scaler = GradScaler('cuda')  # ← Исправлено

    best_val_acc = 0.0
    history = {
        'train_loss': [], 'train_acc': [],
        'val_loss': [], 'val_acc': []
    }

    for epoch in range(epochs):
        # ========== TRAIN ==========
        model.train()
        train_loss, train_correct, train_total = 0, 0, 0

        pbar = tqdm(train_loader, desc=f"Epoch {epoch+1}/{epochs}")
        for images, bio, labels in pbar:
            images = images.to(device, non_blocking=True)
            bio = bio.to(device, non_blocking=True)
            labels = labels.to(device, non_blocking=True)

            optimizer.zero_grad(set_to_none=True)

            with autocast('cuda'):  # ← Исправлено
                outputs = model(images, bio)
                loss = criterion(outputs, labels)

            scaler.scale(loss).backward()
            scaler.step(optimizer)
            scaler.update()

            train_loss += loss.item()
            _, predicted = torch.max(outputs, 1)
            train_total += labels.size(0)
            train_correct += (predicted == labels).sum().item()

            pbar.set_postfix({
                'loss': f'{loss.item():.4f}',
                'acc': f'{100*train_correct/train_total:.1f}%'
            })

        train_loss /= len(train_loader)
        train_acc = 100 * train_correct / train_total

        # ========== VALIDATION ==========
        model.eval()
        val_loss, val_correct, val_total = 0, 0, 0

        with torch.no_grad():
            for images, bio, labels in valid_loader:
                images = images.to(device, non_blocking=True)
                bio = bio.to(device, non_blocking=True)
                labels = labels.to(device, non_blocking=True)

                with autocast('cuda'):
                    outputs = model(images, bio)
                    loss = criterion(outputs, labels)

                val_loss += loss.item()
                _, predicted = torch.max(outputs, 1)
                val_total += labels.size(0)
                val_correct += (predicted == labels).sum().item()

        val_loss /= len(valid_loader)
        val_acc = 100 * val_correct / val_total

        scheduler.step()

        # Logging
        history['train_loss'].append(train_loss)
        history['train_acc'].append(train_acc)
        history['val_loss'].append(val_loss)
        history['val_acc'].append(val_acc)

        print(
            f"\n✅ Epoch {epoch+1}: Train {train_acc:.1f}% | Val {val_acc:.1f}% | LR: {scheduler.get_last_lr()[0]:.2e}")

        # Save best
        if val_acc > best_val_acc:
            best_val_acc = val_acc
            torch.save(model.state_dict(),
                       '/content/drive/MyDrive/best_mobilenet_bio.pth')
            print(f"🏆 New Best: {best_val_acc:.1f}%")

    return history

# ============================================================================
# ЧАСТЬ 10: СОЗДАНИЕ ДАТАСЕТОВ И ЗАПУСК ОБУЧЕНИЯ
# ============================================================================


print("\n" + "=" * 60)
print("🚀 ОБУЧЕНИЕ MobileNetV3 + Biometric Fusion")
print("=" * 60)

# Создаём датасеты С КЭШЕМ
train_dataset = FastFatigueDataset(
    CLASSIFICATION_DATASET_PATH,
    split='train',
    transform=train_transforms,
    bio_cache=bio_cache  # ← Передаём кэш!
)

valid_dataset = FastFatigueDataset(
    CLASSIFICATION_DATASET_PATH,
    split='valid',
    transform=val_transforms,
    bio_cache=bio_cache
)

test_dataset = FastFatigueDataset(
    CLASSIFICATION_DATASET_PATH,
    split='test',
    transform=val_transforms,
    bio_cache=bio_cache
)

# DataLoaders - ОПТИМИЗИРОВАНЫ ДЛЯ COLAB FREE
train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    num_workers=NUM_WORKERS,
    pin_memory=True
    # persistent_workers убран - может вызывать зависания
)

valid_loader = DataLoader(
    valid_dataset,
    batch_size=BATCH_SIZE * 2,
    shuffle=False,
    num_workers=NUM_WORKERS,
    pin_memory=True
)

test_loader = DataLoader(
    test_dataset,
    batch_size=BATCH_SIZE * 2,
    shuffle=False,
    num_workers=NUM_WORKERS,
    pin_memory=True
)

# Создаём модель
model = MobileNetV3BiometricFusion(num_classes=2)
total_params = sum(p.numel() for p in model.parameters())
trainable_params = sum(p.numel()
                       for p in model.parameters() if p.requires_grad)
print(f"\n📊 Параметров: {total_params:,} (обучаемых: {trainable_params:,})")

# Запуск обучения
print("\n⏱️ Ожидаемое время: ~30 сек на эпоху")
history = train_model(model, train_loader, valid_loader,
                      epochs=EPOCHS, lr=LEARNING_RATE)

# ============================================================================
# ЧАСТЬ 11: ТЕСТИРОВАНИЕ И ВИЗУАЛИЗАЦИЯ
# ============================================================================


def evaluate_model(model, test_loader):
    """Полная оценка модели на тестовом наборе"""

    model.eval()
    model.to(device)

    all_preds = []
    all_labels = []
    all_probs = []
    fusion_weights_visual = []
    fusion_weights_bio = []

    with torch.no_grad():
        for images, bio, labels in tqdm(test_loader, desc="Testing"):
            images = images.to(device)
            bio = bio.to(device)

            outputs = model(images, bio)
            probs = torch.softmax(outputs, dim=1)
            _, predicted = torch.max(outputs, 1)

            weights = model.get_fusion_weights(images, bio)

            all_preds.extend(predicted.cpu().numpy())
            all_labels.extend(labels.numpy())
            all_probs.extend(probs[:, 1].cpu().numpy())
            fusion_weights_visual.extend(weights[:, 0].cpu().numpy())
            fusion_weights_bio.extend(weights[:, 1].cpu().numpy())

    return {
        'preds': np.array(all_preds),
        'labels': np.array(all_labels),
        'probs': np.array(all_probs),
        'fusion_visual': np.array(fusion_weights_visual),
        'fusion_bio': np.array(fusion_weights_bio)
    }


# Загружаем лучшую модель
model.load_state_dict(torch.load(
    '/content/drive/MyDrive/best_mobilenet_bio.pth'))
results = evaluate_model(model, test_loader)

# ============================================================================
# ВИЗУАЛИЗАЦИЯ
# ============================================================================

fig = plt.figure(figsize=(16, 12))

# 1. Training curves - Loss
ax1 = fig.add_subplot(2, 2, 1)
ax1.plot(history['train_loss'], label='Train Loss', color='blue')
ax1.plot(history['val_loss'], label='Val Loss', color='orange')
ax1.set_xlabel('Epoch')
ax1.set_ylabel('Loss')
ax1.set_title('Training & Validation Loss')
ax1.legend()
ax1.grid(True, alpha=0.3)

# 2. Training curves - Accuracy
ax2 = fig.add_subplot(2, 2, 2)
ax2.plot(history['train_acc'], label='Train Acc', color='blue')
ax2.plot(history['val_acc'], label='Val Acc', color='orange')
ax2.set_xlabel('Epoch')
ax2.set_ylabel('Accuracy (%)')
ax2.set_title('Training & Validation Accuracy')
ax2.legend()
ax2.grid(True, alpha=0.3)

# 3. Confusion Matrix
ax3 = fig.add_subplot(2, 2, 3)
cm = confusion_matrix(results['labels'], results['preds'])
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=CLASS_NAMES, yticklabels=CLASS_NAMES, ax=ax3)
ax3.set_xlabel('Predicted')
ax3.set_ylabel('True')
ax3.set_title('Confusion Matrix')

# 4. Fusion Weights Distribution
ax4 = fig.add_subplot(2, 2, 4)
ax4.hist(results['fusion_visual'], bins=30, alpha=0.7,
         label='Visual weight', color='blue')
ax4.hist(results['fusion_bio'], bins=30, alpha=0.7,
         label='Bio weight', color='green')
ax4.set_xlabel('Weight')
ax4.set_ylabel('Frequency')
ax4.set_title(
    'Fusion Weights Distribution\n(Какой модальности модель доверяет)')
ax4.legend()
ax4.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('/content/drive/MyDrive/training_results.png', dpi=150)
plt.show()

# Classification Report
print("\n" + "=" * 60)
print("📊 CLASSIFICATION REPORT")
print("=" * 60)
print(classification_report(results['labels'], results['preds'],
                            target_names=CLASS_NAMES, digits=3))

# Fusion Analysis
print("\n📈 FUSION ANALYSIS:")
print(
    f"  Visual weight: mean={results['fusion_visual'].mean():.3f}, std={results['fusion_visual'].std():.3f}")
print(
    f"  Bio weight: mean={results['fusion_bio'].mean():.3f}, std={results['fusion_bio'].std():.3f}")

# ============================================================================
# ЧАСТЬ 12: ЭКСПОРТ В ONNX
# ============================================================================


print("\n📦 Экспорт в ONNX...")

model.to('cpu')
model.eval()

# Dummy inputs
dummy_image = torch.randn(1, 3, 224, 224)
dummy_bio = torch.randn(1, 8)

onnx_path = '/content/drive/MyDrive/mobilenet_bio_fatigue.onnx'

torch.onnx.export(
    model,
    (dummy_image, dummy_bio),
    onnx_path,
    export_params=True,
    opset_version=17,
    do_constant_folding=True,
    input_names=['image', 'biometrics'],
    output_names=['class_logits'],
    dynamic_axes={
        'image': {0: 'batch_size'},
        'biometrics': {0: 'batch_size'},
        'class_logits': {0: 'batch_size'}
    }
)

# Проверка
onnx_model = onnx.load(onnx_path)
onnx.checker.check_model(onnx_model)

file_size = os.path.getsize(onnx_path) / (1024 * 1024)
print(f"✅ Модель экспортирована: {onnx_path}")
print(f"📊 Размер: {file_size:.2f} MB")

print("\n" + "=" * 60)
print("🎉 ГОТОВО!")
print("=" * 60)

# ============================================================================
# ЧАСТЬ 12: ЭКСПОРТ В ЕДИНЫЙ ONNX ФАЙЛ
# ============================================================================

# 1. Устанавливаем библиотеки (на случай если их нет)
!pip install onnx onnxscript onnxruntime - q


print("\n📦 Экспорт в ONNX...")

# Переключаем модель на CPU для экспорта
model.to('cpu')
model.eval()

# Создаем пустышки данных
dummy_image = torch.randn(1, 3, 224, 224)
dummy_bio = torch.randn(1, 8)

# Временное и финальное имена файлов
temp_onnx_path = 'temp_model.onnx'
final_onnx_path = '/content/drive/MyDrive/mobilenet_bio_fatigue.onnx'

# --- ШАГ 1: Черновой экспорт ---
print("⏳ Шаг 1: Конвертация PyTorch -> ONNX...")
torch.onnx.export(
    model,
    (dummy_image, dummy_bio),
    temp_onnx_path,
    export_params=True,
    opset_version=17,
    do_constant_folding=True,
    input_names=['image', 'biometrics'],
    output_names=['class_logits'],
    dynamic_axes={
        'image': {0: 'batch_size'},
        'biometrics': {0: 'batch_size'},
        'class_logits': {0: 'batch_size'}
    }
)

# --- ШАГ 2: Склейка в один файл ---
print("⏳ Шаг 2: Сборка в единый файл (встраивание весов)...")
try:
    # Загружаем модель
    model_proto = onnx.load(temp_onnx_path)

    # Пересохраняем, явно запрещая внешние данные
    onnx.save_model(
        model_proto,
        final_onnx_path,
        save_as_external_data=False  # <--- ВОТ ЭТО ГЛАВНАЯ КОМАНДА
    )

    # Удаляем временный файл
    if os.path.exists(temp_onnx_path):
        os.remove(temp_onnx_path)
    # Удаляем мусорный .data файл, если он создался на шаге 1
    if os.path.exists(temp_onnx_path + ".data"):
        os.remove(temp_onnx_path + ".data")

    # Проверка результата
    file_size = os.path.getsize(final_onnx_path) / (1024 * 1024)
    print(f"\n✅ ГОТОВО! Файл сохранен: {final_onnx_path}")
    print(f"📊 Размер: {file_size:.2f} MB")
    print("Теперь это ОДИН файл, который можно скачивать.")

except Exception as e:
    print(f"❌ Ошибка при склейке: {e}")
